### ISSUE TITLE
Created an exploratory and expository figure in R markdown

### ISSUE THREAD

**Issue by jezellaperaza** [jezellaperaza/Assignment-5#1]
In this assignment, I created an exploratory figure that shows the density of the different lengths (mm) between sexes of Siscowet Lake Trout in Lake Superior, Michigan. Following that figure, I decided to add a bit more information such as a histogram, and separate density and lengths between males and females. I also made sure to use appropriate labels and accessible colors in my expository figures. 

You can find these two figures in the R markdown file titled Assignment-5_Figures.rmd in the Assignment-5 repo. under the figures folder. OR you can find the R markdown file using this URL attached to my repo: https://jezellaperaza.github.io/Assignment-5/

**Comment by mdscheuerell** [comment]
I really like your histograms with the density plots overlaid—nice work, Jezella!

And nice job putting together an html version and displaying it with GitHub Pages!
